#ifndef NETWORK_SIDEBAR_AMNEZIAWG_H
#define NETWORK_SIDEBAR_AMNEZIAWG_H

#include <glib.h>

G_BEGIN_DECLS

#define NETWORK_SIDEBAR_AMNEZIAWG_CONFIG_DIR "/etc/amnezia/amneziawg"
#define NETWORK_SIDEBAR_AMNEZIAWG_STAGING_DIR "/etc/amnezia/amneziawg/.staging"
#define NETWORK_SIDEBAR_AMNEZIAWG_RUNTIME_DIR "/run/nm-sidebar/amneziawg"
#define NETWORK_SIDEBAR_AMNEZIAWG_RUNTIME_CONFIG_DIR "/run/nm-sidebar/amneziawg/.configs"
#define NETWORK_SIDEBAR_AMNEZIAWG_MAX_INTERFACE_LENGTH 15
#define NETWORK_SIDEBAR_AMNEZIAWG_LINK_TOKEN_LENGTH 32
#define NETWORK_SIDEBAR_AMNEZIAWG_LINK_ALIAS_PREFIX "nm-sidebar-awg-"
#define NETWORK_SIDEBAR_AMNEZIAWG_MAX_CONFIG_SIZE (1024u * 1024u)
#define NETWORK_SIDEBAR_AMNEZIAWG_DBUS_NAME "dev.relz.NmSidebar.AmneziaWG"
#define NETWORK_SIDEBAR_AMNEZIAWG_DBUS_PATH "/dev/relz/NmSidebar/AmneziaWG"
#define NETWORK_SIDEBAR_AMNEZIAWG_DBUS_INTERFACE "dev.relz.NmSidebar.AmneziaWG"
#define NETWORK_SIDEBAR_AMNEZIAWG_DBUS_EXECUTE "Execute"
#define NETWORK_SIDEBAR_AMNEZIAWG_DBUS_LIST_PROFILES "ListProfiles"
#define NETWORK_SIDEBAR_AMNEZIAWG_OPERATION_IMPORT "import"
#define NETWORK_SIDEBAR_AMNEZIAWG_OPERATION_REPLACE "replace"
#define NETWORK_SIDEBAR_AMNEZIAWG_OPERATION_UP "up"
#define NETWORK_SIDEBAR_AMNEZIAWG_OPERATION_DOWN "down"
#define NETWORK_SIDEBAR_AMNEZIAWG_OPERATION_DELETE "delete"
#define NETWORK_SIDEBAR_AMNEZIAWG_OPERATION_LIST_PROFILES "list-profiles"
#define NETWORK_SIDEBAR_AMNEZIAWG_PROFILE_REPORT_MAGIC "NM-SIDEBAR-AWG-PROFILES"
#define NETWORK_SIDEBAR_AMNEZIAWG_PROFILE_REPORT_VERSION 1
#define NETWORK_SIDEBAR_AMNEZIAWG_PROFILE_REPORT_MAX_RECORDS 256
#define NETWORK_SIDEBAR_AMNEZIAWG_PROFILE_REPORT_MAX_SIZE 8192

typedef enum {
  NETWORK_SIDEBAR_AMNEZIAWG_CAPABILITY_NONE = 0,
  NETWORK_SIDEBAR_AMNEZIAWG_CAPABILITY_HELPER = 1u << 0,
  NETWORK_SIDEBAR_AMNEZIAWG_CAPABILITY_AWG_QUICK = 1u << 1,
} NetworkSidebarAmneziaWGCapability;

typedef struct {
  gboolean named_exists;
  guint named_ifindex;
  guint token_matches;
  guint token_ifindex;
  gboolean token_has_expected_name;
  char token_ifname[NETWORK_SIDEBAR_AMNEZIAWG_MAX_INTERFACE_LENGTH + 1];
} NetworkSidebarAmneziaWGLinkObservation;

typedef enum {
  /* Passed preliminary profile checks, not protocol validation; runtime state
   * and dependencies still gate activation attempts. */
  NETWORK_SIDEBAR_AMNEZIAWG_PROFILE_AVAILABLE = 0,
  NETWORK_SIDEBAR_AMNEZIAWG_PROFILE_FILE_SECURITY = 1,
  NETWORK_SIDEBAR_AMNEZIAWG_PROFILE_INVALID_CONFIGURATION = 2,
  /* Rejected during strip preprocessing or runtime snapshot construction. */
  NETWORK_SIDEBAR_AMNEZIAWG_PROFILE_INCOMPATIBLE_CONFIGURATION = 3,
  NETWORK_SIDEBAR_AMNEZIAWG_PROFILE_CHANGED_OR_UNREADABLE = 4,
} NetworkSidebarAmneziaWGProfileStatus;

/* These values are the complete public exit-status contract for the helper. */
typedef enum {
  NETWORK_SIDEBAR_AMNEZIAWG_HELPER_SUCCESS = 0,
  NETWORK_SIDEBAR_AMNEZIAWG_HELPER_USAGE = 2,
  NETWORK_SIDEBAR_AMNEZIAWG_HELPER_NOT_ROOT = 3,
  NETWORK_SIDEBAR_AMNEZIAWG_HELPER_INVALID_NAME = 4,
  NETWORK_SIDEBAR_AMNEZIAWG_HELPER_INPUT_TOO_LARGE = 5,
  NETWORK_SIDEBAR_AMNEZIAWG_HELPER_INVALID_CONFIG = 6,
  NETWORK_SIDEBAR_AMNEZIAWG_HELPER_REPLACE_CONFIRMATION_REQUIRED = 7,
  NETWORK_SIDEBAR_AMNEZIAWG_HELPER_NOT_FOUND = 8,
  NETWORK_SIDEBAR_AMNEZIAWG_HELPER_ACTIVE = 9,
  NETWORK_SIDEBAR_AMNEZIAWG_HELPER_INTERFACE_CONFLICT = 10,
  NETWORK_SIDEBAR_AMNEZIAWG_HELPER_AWG_QUICK_UNAVAILABLE = 11,
  NETWORK_SIDEBAR_AMNEZIAWG_HELPER_AWG_QUICK_FAILED = 12,
  NETWORK_SIDEBAR_AMNEZIAWG_HELPER_FILESYSTEM_FAILED = 13,
  NETWORK_SIDEBAR_AMNEZIAWG_HELPER_RUNTIME_FAILED = 14,
  NETWORK_SIDEBAR_AMNEZIAWG_HELPER_ROLLBACK_FAILED = 15,
  NETWORK_SIDEBAR_AMNEZIAWG_HELPER_INPUT_FAILED = 16,
  NETWORK_SIDEBAR_AMNEZIAWG_HELPER_CHILD_SETUP_FAILED = 17,
  NETWORK_SIDEBAR_AMNEZIAWG_HELPER_INTERFACE_CREATION_FAILED = 18,
  NETWORK_SIDEBAR_AMNEZIAWG_HELPER_USERSPACE_FAILED = 19,
  NETWORK_SIDEBAR_AMNEZIAWG_HELPER_SETCONF_FAILED = 20,
  NETWORK_SIDEBAR_AMNEZIAWG_HELPER_ADDRESS_FAILED = 21,
  NETWORK_SIDEBAR_AMNEZIAWG_HELPER_MTU_FAILED = 22,
  NETWORK_SIDEBAR_AMNEZIAWG_HELPER_DNS_FAILED = 23,
  NETWORK_SIDEBAR_AMNEZIAWG_HELPER_ROUTE_FAILED = 24,
  NETWORK_SIDEBAR_AMNEZIAWG_HELPER_FIREWALL_FAILED = 25,
  NETWORK_SIDEBAR_AMNEZIAWG_HELPER_CHILD_SIGNALED = 26,
  NETWORK_SIDEBAR_AMNEZIAWG_HELPER_DNS_BACKEND_UNAVAILABLE = 27,
  NETWORK_SIDEBAR_AMNEZIAWG_HELPER_DNS_APPLY_FAILED = 28,
  NETWORK_SIDEBAR_AMNEZIAWG_HELPER_DNS_REVERT_FAILED = 29,
  NETWORK_SIDEBAR_AMNEZIAWG_HELPER_DNS_ROLLBACK_FAILED = 30,
  NETWORK_SIDEBAR_AMNEZIAWG_HELPER_INVENTORY_PARTIAL = 31,
  NETWORK_SIDEBAR_AMNEZIAWG_HELPER_TIMED_OUT = 32,
  NETWORK_SIDEBAR_AMNEZIAWG_HELPER_FIREWALL_CLEANUP_FAILED = 33,
  NETWORK_SIDEBAR_AMNEZIAWG_HELPER_SWITCH_CLEANUP_FAILED = 34,
} NetworkSidebarAmneziaWGHelperExit;

/* Names use an ASCII alphanumeric first byte and ASCII alphanumeric, '.',
 * '_', or '-' thereafter. */
gboolean network_sidebar_amneziawg_name_is_valid(const char *name);
gboolean network_sidebar_amneziawg_profile_status_is_valid(guint status);
gboolean network_sidebar_amneziawg_profile_status_allows_removal(
  NetworkSidebarAmneziaWGProfileStatus status);
gboolean network_sidebar_amneziawg_helper_exit_is_valid(guint status);

/* Uses the basename, removes a case-insensitive .conf suffix, replaces runs of
 * unsafe bytes with '-', and truncates to the interface-name limit. */
char *network_sidebar_amneziawg_interface_from_filename(const char *filename);
gboolean network_sidebar_amneziawg_link_token_is_valid(const char *token);

void network_sidebar_amneziawg_secret_wipe(void *data, gsize length);
void network_sidebar_amneziawg_secret_free(guint8 *data, gsize length);

G_END_DECLS

#endif
